# Generated by Django 5.1.3 on 2024-11-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': 'Alumni'},
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='company',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='current_job',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='linkedin_profile',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='alumni',
            name='current_position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='degree',
            field=models.CharField(choices=[('BSC', 'Bachelor of Science'), ('BA', 'Bachelor of Arts'), ('MSC', 'Master of Science'), ('MSC', 'Master of Science'), ('PHD', 'Doctor of Philosophy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
