# Generated by Django 5.1.3 on 2024-11-22 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='max_participants',
        ),
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.ManyToManyField(blank=True, related_name='events_participating', to=settings.AUTH_USER_MODEL),
        ),
    ]
