# Generated by Django 5.1.3 on 2024-11-22 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_notification'),
        ('events', '0003_event_is_virtual_remove_event_max_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipation',
            name='alumni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='alumni.alumni'),
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='events.event'),
        ),
    ]
